"""create reciprocal_pairs table

Revision ID: a9f4896d337e
Revises: d51702731338
Create Date: 2026-08-19 15:16:54.913472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f4896d337e'
down_revision: Union[str, None] = 'd51702731338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reciprocal_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair_id', sa.String(length=20), nullable=False),
    sa.Column('request_a_id', sa.Integer(), nullable=False),
    sa.Column('request_b_id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_difference_ms', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'RESOLVED', 'ALLOWED', 'BLOCKED', name='pairstatus'), server_default='DETECTED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_a_id'], ['communication_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_b_id'], ['communication_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_a_id', name='uq_reciprocal_pairs_request_a'),
    sa.UniqueConstraint('request_b_id', name='uq_reciprocal_pairs_request_b')
    )
    op.create_index(op.f('ix_reciprocal_pairs_id'), 'reciprocal_pairs', ['id'], unique=False)
    op.create_index(op.f('ix_reciprocal_pairs_pair_id'), 'reciprocal_pairs', ['pair_id'], unique=True)
    op.create_index(op.f('ix_reciprocal_pairs_request_a_id'), 'reciprocal_pairs', ['request_a_id'], unique=False)
    op.create_index(op.f('ix_reciprocal_pairs_request_b_id'), 'reciprocal_pairs', ['request_b_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reciprocal_pairs_request_b_id'), table_name='reciprocal_pairs')
    op.drop_index(op.f('ix_reciprocal_pairs_request_a_id'), table_name='reciprocal_pairs')
    op.drop_index(op.f('ix_reciprocal_pairs_pair_id'), table_name='reciprocal_pairs')
    op.drop_index(op.f('ix_reciprocal_pairs_id'), table_name='reciprocal_pairs')
    op.drop_table('reciprocal_pairs')
    # ### end Alembic commands ###
