"""create communication_requests table

Revision ID: d51702731338
Revises: f96e96156b89
Create Date: 2026-08-05 11:52:04.869314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51702731338'
down_revision: Union[str, None] = 'f96e96156b89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=20), nullable=False),
    sa.Column('caller_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('request_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CANCELLED', 'EXPIRED', 'MATCHED', 'ALLOWED', 'BLOCKED', 'COMPLETED', name='requeststatus'), server_default='PENDING', nullable=False),
    sa.Column('reciprocal_flag', sa.Boolean(), nullable=False),
    sa.Column('pair_id', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caller_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_requests_caller_id'), 'communication_requests', ['caller_id'], unique=False)
    op.create_index(op.f('ix_communication_requests_id'), 'communication_requests', ['id'], unique=False)
    op.create_index(op.f('ix_communication_requests_receiver_id'), 'communication_requests', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_communication_requests_request_id'), 'communication_requests', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communication_requests_request_id'), table_name='communication_requests')
    op.drop_index(op.f('ix_communication_requests_receiver_id'), table_name='communication_requests')
    op.drop_index(op.f('ix_communication_requests_id'), table_name='communication_requests')
    op.drop_index(op.f('ix_communication_requests_caller_id'), table_name='communication_requests')
    op.drop_table('communication_requests')
    # ### end Alembic commands ###
